name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.PORT }} -H ${{ secrets.HOSTNAME }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          rsync -avz -e "ssh -p ${{ secrets.PORT }}" --exclude '.git' . ${{ secrets.USER }}@${{ secrets.HOSTNAME }}:/home/${{ secrets.USER }}/toto
          ssh -p ${{ secrets.PORT }} ${{ secrets.USER }}@${{ secrets.HOSTNAME }} 'cd ./toto && ./deploy.sh'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER: ${{ secrets.USER }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          PORT: ${{ secrets.PORT }}
